name: Continuous Integration

#this is trigger CI on push and PR for main branch only
#on:
#  push:
#   branches: [main]
#  pull_request:
#   branches: [main]

# this is trigger CI on all kinds of branches and PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '22.14.0'
    - name: install deps
      run: npm install